### ISSUE TITLE
problem1

### ISSUE THREAD

**Issue by wilson2016** [gitstliu/go-redis-cluster#1]
can not connect to ip and port
StartNodes: []string{"127.0.0.1:7000", "127.0.0.1:7001", "127.0.0.1:7002"}
I replace it by my ip and port,but it doesn't work!

**Comment by qinze118** [comment]
it's need to auth

**Comment by qinze118** [comment]
you can add auth under update func()

**Comment by gitstliu** [comment]
@wilson2016 Is there any error reported?

**Comment by gitstliu** [comment]
No issue reported
